package com.myself.spring.mybatis.mbg.mapper;

import com.myself.spring.mybatis.mbg.pojo.Employee;
import java.util.List;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Jul 23 11:22:27 GMT+08:00 2022
     */
    int deleteByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Jul 23 11:22:27 GMT+08:00 2022
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Jul 23 11:22:27 GMT+08:00 2022
     */
    Employee selectByPrimaryKey(Integer eid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Jul 23 11:22:27 GMT+08:00 2022
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_emp
     *
     * @mbggenerated Sat Jul 23 11:22:27 GMT+08:00 2022
     */
    int updateByPrimaryKey(Employee record);
}